### ISSUE TITLE
feature request: two-way import/update MSP<->redmine

### ISSUE THREAD

**Issue by alexeyOnGitHub** [suer/redmine_ms_projects#1]
hi!
have you considered updating tasks status from redmine to MSP?

**Comment by rainman-ph** [comment]
Readmine has a RESTful api in php and ruby. I'm exploring creating a vbasic for application. see some reference I found as a starting point:
http://stackoverflow.com/questions/545790/how-to-call-web-service-using-vbscript-synchronous
http://www.tushar-mehta.com/publish_train/xl_vba_cases/vba_web_pages_services/

**Comment by alexeyOnGitHub** [comment]
I created my own application for two-way synchronization between Redmine and MS Project: http://taskadapter.com
